### ISSUE TITLE
QC.Ver: get_git_tags.py fails even when repository already has defined tags

### ISSUE THREAD

**Issue by rjdmartins** [EOSC-synergy/sqaaas-tooling#104]
get_git_tags.py fails during online assessment  to test https://github.com/rjdmartins/try_ibergrid2022_sqaaas/ due to the following error:

> + docker-compose -f .sqa/docker-compose.yml --project-directory /jenkins/workspace/id2022_sqaaas.assess.sqaaas_main/ exec -T qc.ver_sleepy-ruby-vole /usr/bin/env sh .sqa/script.woolly-pear-monkey.sh
> Traceback (most recent call last):
>   File "/usr/bin/get_git_tags.py", line 44, in <module>
>     print(main())
>   File "/usr/bin/get_git_tags.py", line 42, in main
>     return get_tags(repo)
>   File "/usr/bin/get_git_tags.py", line 32, in get_tags
>     tags = sorted(repo.tags, key=lambda t: t.commit.committed_datetime)
>   File "/usr/bin/get_git_tags.py", line 32, in <lambda>
>     tags = sorted(repo.tags, key=lambda t: t.commit.committed_datetime)
>   File "/usr/local/lib/python3.9/site-packages/git/refs/tag.py", line 43, in commit
>     obj = self.object
>   File "/usr/local/lib/python3.9/site-packages/git/refs/tag.py", line 69, in object
>     return Reference._get_object(self)
>   File "/usr/local/lib/python3.9/site-packages/git/refs/symbolic.py", line 210, in _get_object
>     return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
>   File "/usr/local/lib/python3.9/site-packages/git/objects/base.py", line 85, in new_from_sha
>     oinfo = repo.odb.info(sha1)
>   File "/usr/local/lib/python3.9/site-packages/git/db.py", line 43, in info
>     hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
>   File "/usr/local/lib/python3.9/site-packages/git/cmd.py", line 1253, in get_object_header
>     return self.__get_object_header(cmd, ref)
>   File "/usr/local/lib/python3.9/site-packages/git/cmd.py", line 1240, in __get_object_header
>     return self._parse_object_header(cmd.stdout.readline())
>   File "/usr/local/lib/python3.9/site-packages/git/cmd.py", line 1198, in _parse_object_header
>     raise ValueError("SHA could not be resolved, git returned: %r" % (header_line.strip()))
> ValueError: SHA could not be resolved, git returned: b''

Log: https://jenkins.eosc-synergy.eu/job/eosc-synergy-org/job/try_ibergrid2022_sqaaas.assess.sqaaas/job/main/13/execution/node/133/log/

The Online Assessment result fail at QC.Ver01.0 (The code repository does not use tags for releasing new software versions) and QC.Ver01 (Latest release tag <None> found, but is not SemVer compliantMore ), but weirdly gets success at QC.Ver02 (All release tags are SemVer compliant).

**Comment by orviz** [comment]
@rjdmartins could you check again? the issue should be solved

**Comment by orviz** [comment]
@rjdmartins closing the issue, let us know if the problem persists
