### ISSUE TITLE
(Suggestion) QC.Sty and QC.Doc: Relax some conditions during validation

### ISSUE THREAD

**Issue by rjdmartins** [EOSC-synergy/sqaaas-tooling#105]
In QC.Sty and QC.Doc, some conditions are too 'demanding' and need to be relaxed during validation.

For example, one of the problems I found during QC.Sty and QC.Doc tests were with "line lengths". Both cases limit the size to 80 characters. 
In QC.Doc, in markdownlint,  the error is MD013 - Line length
In QC.Sty, in flake8, the error is E501: Line too long
In my opinion, both must be excluded from validation to ease up validation. And in some cases, these limits do not make any sense for today standards.

**Comment by mariojmdavid** [comment]
hi put this files in your repo
https://github.com/indigo-dc/udocker/blob/devel3/.mdlrc
https://github.com/indigo-dc/udocker/blob/devel3/.flake8

if need check the code of conduct
https://github.com/indigo-dc/udocker/blob/devel3/CODE_OF_CONDUCT.md

**Comment by rjdmartins** [comment]
@mariojmdavid Thank you for providing the files
